name: bank_app
description: "Banking application"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.3.1
  dio: ^5.9.2
  go_router: ^17.1.0
  json_annotation: ^4.11.0
  flutter_secure_storage: ^10.0.0
  google_fonts: ^8.0.2
  flutter_svg: ^2.2.4
  geolocator: ^14.0.0
  google_maps_flutter: ^2.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true
  assets:
    # svg file
    - assets/svg/category/
    - assets/svg/icons/
    - assets/svg/navigation_bar/
    - assets/svg/flags/
    - assets/svg/Illustration/